#Application name
spring.application.name=demo
#Stores data in file instead of temporary memory
spring.datasource.url=jdbc:h2:file:./data/employeedb
#Specifies the H2 jdbc driver
spring.datasource.driverClassName=org.h2.Driver
#Dedfault H2 username
spring.datasource.username=sa
#Empty password (fine for development)
spring.datasource.password=

#Enables the H2 web console
spring.h2.console.enabled=true
#Access console at /h2-console
spring.h2.console.path=/h2-console

#Preserves data and updates schema
spring.jpa.hibernate.ddl-auto=update
#Prints SQL queries in the console (Helpful for learning)
spring.jpa.show-sql=true